### ISSUE TITLE
I know how to go back to the tool you were using

### ISSUE THREAD

**Issue by TaranVH** [Arjasonjai/Autohotkey#1]
I noticed that it's a thing you might want to know how to do. Here's my current code:

;Disable single clip at cursor - must turn this into a proper function.
Xbutton2::
F8::
send, ^!d ;ctrl alt d is DESELECT
send, v ;selection tool
send, {alt down}
send, {lbutton}
send, {alt up}
send, {home} ;disable
sleep 10
;I have a fancy way of figuring out which tool i WAS using. Is just be a thing that listens for v t r y b x h p and saves that as a string.

send, %currentTool%
return

;============== CURRENT TOOL REMEMBERER ================

;IMPORTANT - these are MY keyboard assignments for tools in premiere
;Your own assignments will probably be different!
~v::
~t::
~r::
~y::
~b::
~x::
~h::
~p::
currentTool = %A_thishotkey% ;so, %currentTool% might become r or y or v. Whatever the last tool is that I selected.
return

**Comment by Arjasonjai** [comment]
Cool, will check that out!
